CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    EMAIL TEXT, 
    USERNAME TEXT, 
    PASSWORDHASH TEXT, 
    TOKEN TEXT, 
    IMG TEXT DEFAULT NULL,
    BG TEXT DEFAULT NULL,
    BIO TEXT DEFAULT NULL,
    ADDR TEXT DEFAULT NULL
);

CREATE TABLE POSTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER,
    TEXT TEXT,
    IMG TEXT,
    CREATED_DATE DATE,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID)
);

CREATE TABLE COMMENTS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER,
    POST_ID INTEGER,
    COMMENT_TEXT TEXT,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(ID)
);

CREATE TABLE LIKES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    USER_ID INTEGER,
    POST_ID INTEGER,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(ID),
    UNIQUE(USER_ID, POST_ID)
);

CREATE TABLE FOLLOWERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    FOLLOWED_ID INTEGER,
    FOLLOWER_ID INTEGER,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FOLLOWED_ID) REFERENCES USERS(ID),
    FOREIGN KEY (FOLLOWER_ID) REFERENCES USERS(ID),
    UNIQUE(FOLLOWED_ID, FOLLOWER_ID)
);

CREATE TABLE NOTIFICATIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    TEXT TEXT,
    TYPE INTEGER,
    USER_ID INTEGER,
    ACTOR_ID INTEGER,
    SEEN INTEGER DEFAULT 0,
    POST_ID INTEGER,
    LINK TEXT,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ACTOR_ID) REFERENCES USERS(ID),
    FOREIGN KEY (POST_ID) REFERENCES POSTS(ID)
);

CREATE TABLE CONVERSATIONS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT, 
    FIRST_USER_ID INTEGER,
    SECOND_USER_ID INTEGER,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (FIRST_USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (SECOND_USER_ID) REFERENCES USERS(ID),
    UNIQUE(FIRST_USER_ID, SECOND_USER_ID)
);

CREATE TABLE MESSAGES (
    ID INTEGER PRIMARY KEY AUTOINCREMENT,
    MESSAGE TEXT,
    MESSAGE_TYPE TEXT,
    CONVERSATION_ID INTEGER,
    SENDER_ID INTEGER,
    RECEIVER_ID INTEGER,
    CREATED_DATE DATE DEFAULT CURRENT_TIMESTAMP,
    SEEN INTEGER DEFAULT 0,
    FOREIGN KEY (CONVERSATION_ID) REFERENCES CONVERSATIONS(ID),
    FOREIGN KEY (SENDER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (RECEIVER_ID) REFERENCES USERS(ID)
);
